# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phenovis_read_mask <- function(maskname) {
    invisible(.Call(`_phenovisr_phenovis_read_mask`, maskname))
}

phenovis_get_histogram <- function(names, number_of_bins) {
    .Call(`_phenovisr_phenovis_get_histogram`, names, number_of_bins)
}

phenovis_get_gcc_histogram <- function(names, number_of_bins) {
    .Call(`_phenovisr_phenovis_get_gcc_histogram`, names, number_of_bins)
}

