# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phenovis_read_mask <- function(maskname) {
    invisible(.Call(`_phenovisr_phenovis_read_mask`, maskname))
}

phenovis_get_mean_gcc <- function(images) {
    .Call(`_phenovisr_phenovis_get_mean_gcc`, images)
}

phenovis_get_metrics <- function(images) {
    .Call(`_phenovisr_phenovis_get_metrics`, images)
}

