# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phenovis_red <- function() {
    .Call(`_phenovisr_phenovis_red`)
}

phenovis_green <- function() {
    .Call(`_phenovisr_phenovis_green`)
}

phenovis_blue <- function() {
    .Call(`_phenovisr_phenovis_blue`)
}

phenovis_H <- function() {
    .Call(`_phenovisr_phenovis_H`)
}

phenovis_read_mask <- function(maskname) {
    invisible(.Call(`_phenovisr_phenovis_read_mask`, maskname))
}

phenovis_get_histogram <- function(mtype, names, number_of_bins) {
    .Call(`_phenovisr_phenovis_get_histogram`, mtype, names, number_of_bins)
}

